<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'id' => '1',
                'name' => 'ジーンズ',
                'image' => 'jeans_1.jpg',
                'price' => '4000',
                'category_id' => '7',
                'target' => '1',
                'color_id' => '2',
                'size_id' => '2',
                'pick_up' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '2',
                'name' => 'パーカー',
                'image' => 'parker_1.jpg',
                'price' => '3000',
                'category_id' => '2',
                'target' => '1',
                'color_id' => '6',
                'size_id' => '3',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '3',
                'name' => 'シャツ1',
                'image' => 'shirt_1.jpg',
                'price' => '2000',
                'category_id' => '2',
                'target' => '1',
                'color_id' => '6',
                'size_id' => '3',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '4',
                'name' => 'シャツ２',
                'image' => 'shirt_2.jpg',
                'price' => '2500',
                'category_id' => '2',
                'target' => '1',
                'color_id' => '7',
                'size_id' => '3',
                'pick_up' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '5',
                'name' => 'ワンピース1',
                'image' => 'women_one_piece_1.jpg',
                'price' => '3000',
                'category_id' => '6',
                'target' => '2',
                'color_id' => '5',
                'size_id' => '2',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '6',
                'name' => 'アウター1',
                'image' => 'women_outer_1.jpg',
                'price' => '7000',
                'category_id' => '1',
                'target' => '2',
                'color_id' => '1',
                'size_id' => '3',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '7',
                'name' => '子供用トップス1',
                'image' => 'kids_tops_1.jpg',
                'price' => '1980',
                'category_id' => '2',
                'target' => '0',
                'color_id' => '3',
                'size_id' => '2',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '8',
                'name' => 'ジーンズ1',
                'image' => 'women_jeans_1.jpg',
                'price' => '3980',
                'category_id' => '3',
                'target' => '2',
                'color_id' => '2',
                'size_id' => '1',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '9',
                'name' => 'トップス1',
                'image' => 'women_tops_1.jpg',
                'price' => '2980',
                'category_id' => '2',
                'target' => '2',
                'color_id' => '2',
                'size_id' => '2',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '10',
                'name' => 'マーメイドスカート1',
                'image' => 'women_skirt_1.jpg',
                'price' => '3580',
                'category_id' => '5',
                'target' => '2',
                'color_id' => '5',
                'size_id' => '1',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '11',
                'name' => 'ワイドパンツ1',
                'image' => 'women_widepants_1.jpg',
                'price' => '3480',
                'category_id' => '3',
                'target' => '2',
                'color_id' => '4',
                'size_id' => '2',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '12',
                'name' => 'インナー1',
                'image' => 'women_inner_1.jpg',
                'price' => '1200',
                'category_id' => '4',
                'target' => '2',
                'color_id' => '2',
                'size_id' => '2',
                'pick_up' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '13',
                'name' => 'ルーム1',
                'image' => 'women_room_1.jpg',
                'price' => '1980',
                'category_id' => '8',
                'target' => '2',
                'color_id' => '3',
                'size_id' => '1',
                'pick_up' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '14',
                'name' => 'インナー1',
                'image' => 'men_inner_1.jpg',
                'price' => '980',
                'category_id' => '4',
                'target' => '1',
                'color_id' => '5',
                'size_id' => '2',
                'pick_up' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '15',
                'name' => 'パンツ1',
                'image' => 'men_pants_1.jpg',
                'price' => '3980',
                'category_id' => '3',
                'target' => '1',
                'color_id' => '3',
                'size_id' => '3',
                'pick_up' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '16',
                'name' => 'スウェット1',
                'image' => 'men_sweat_1.jpg',
                'price' => '2980',
                'category_id' => '9',
                'target' => '1',
                'color_id' => '3',
                'size_id' => '3',
                'pick_up' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
